### ISSUE TITLE
@ZosImage does not work

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/galasa.dev#582]
Setting this as per https://galasa.dev/docs/writing-own-tests/binding-tests#gatsby-focus-wrapper with my zos images set.

It does not pick up the image for use.

Error is

20/02/2023 15:08:57.500 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.zos.internal.ZosManagerImpl
        at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:478) ~[-1676905729865:?]
        at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1676905729865:?]
        at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1676905729865:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:236) [galasa-boot.jar:?]
        at dev.galasa.boot.Launcher.launch(Launcher.java:166) [galasa-boot.jar:?]
        at dev.galasa.boot.Launcher.main(Launcher.java:120) [galasa-boot.jar:?]
Caused by: dev.galasa.zos.ZosManagerException: Unable to locate zOS images for cluster DEFAULT, see property zos.cluster.*.images
        at dev.galasa.zos.internal.properties.ClusterImages.get(ClusterImages.java:39) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.selectNewImage(ZosManagerImpl.java:380) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:327) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:274) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.provisionGenerate(ZosManagerImpl.java:234) ~[?:?]
        at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1676905729865:?]
        ... 9 more

**Comment by hobbit1983** [comment]
Hi @ChrisAtkinson1 can you share what imageTag you are using in your annotations and the set of properties you are running with please

**Comment by ChrisAtkinson1** [comment]
@ZosImage(imageTag="PLEX2")
   public IZosImage zosImage;


zos.cluster.PLEX2.images=MV2D,MV2C
# Define the image called MYTESTIMAGE. If using as a template you will need to fill in any <XXX>
zos.image.MV2C.default.hostname=winmvs2c.hursley.ibm.com
zos.image.MV2C.ipv4.hostname=winmvs2c.hursley.ibm.com
zos.image.MV2C.sysplex=PLEX2
zos.image.MV2C.telnet.port=992
zos.image.MV2C.telnet.tls=true
zos.image.MV2C.max.slots=4
zos.image.MV2C.credentials=MV2C
zos.image.MV2C.clusterid=PLEX2



zos.image.MV2D.default.hostname=winmvs2d.hursley.ibm.com
zos.image.MV2D.ipv4.hostname=winmvs2d.hursley.ibm.com
zos.image.MV2D.sysplex=PLEX2
zos.image.MV2D.telnet.port=992
zos.image.MV2D.telnet.tls=true
zos.image.MV2D.max.slots=4
zos.image.MV2D.credentials=MV2D
zos.image.MV2D.clusterid=PLEX2

**Comment by techcobweb** [comment]
Is it wise to share this stuff on a public github repo ? @ChrisAtkinson1 @hobbit1983
